### ISSUE TITLE
Bug: no items showing

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply-client#264]
The list of items doesn't show in the add item modal.

There's a server error with the following error in the console:
```
 Uncaught exception in the request handler for "POST http://localhost:4000/":

Error: Unsupported
    at _callee$ (webpack://@openmsupply-client/host/../mock-server/src/worker/handlers.ts?:180:23)
    at tryCatch (webpack://@openmsupply-client/host/../../node_modules/regenerator-runtime/runtime.js?:63:40)
    at Generator.invoke [as _invoke] (webpack://@openmsupply-client/host/../../node_modules/regenerator-runtime/runtime.js?:294:22)
    at Generator.eval [as next] (webpack://@openmsupply-client/host/../../node_modules/regenerator-runtime/runtime.js?:119:21)
    at asyncGeneratorStep (webpack://@openmsupply-client/host/../mock-server/src/worker/handlers.ts?:15:28)
    at _next (webpack://@openmsupply-client/host/../mock-server/src/worker/handlers.ts?:33:17)
    at eval (webpack://@openmsupply-client/host/../mock-server/src/worker/handlers.ts?:38:13)
    at new Promise (<anonymous>)
    at eval (webpack://@openmsupply-client/host/../mock-server/src/worker/handlers.ts?:30:16)
    at RestHandler.eval (webpack://@openmsupply-client/host/../../node_modules/msw/lib/esm/RequestHandler-deps.js?:633:61)
```

On the Invoice detail view there are no items, and this returned by the API on the demo server
```
{"errors":[{"message":"Cannot query field \"invoiceByInvoiceNumber\" on type \"Query\".","locations":[{"line":3,"column":5}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"invoiceByInvoiceNumber\" on type \"Query\".","    at Object.Field (C:\\github\\openmsupply-client\\node_modules\\graphql\\validation\\rules\\FieldsOnCorrectTypeRule.js:48:31)","    at Object.enter (C:\\github\\openmsupply-client\\node_modules\\graphql\\language\\visitor.js:323:29)","    at Object.enter (C:\\github\\openmsupply-client\\node_modules\\graphql\\utilities\\TypeInfo.js:370:25)","    at visit (C:\\github\\openmsupply-client\\node_modules\\graphql\\language\\visitor.js:243:26)","    at Object.validate (C:\\github\\openmsupply-client\\node_modules\\graphql\\validation\\validate.js:69:24)","    at validate (C:\\github\\openmsupply-client\\node_modules\\apollo-server-core\\src\\requestPipeline.ts:452:12)","    at Object.processGraphQLRequest (C:\\github\\openmsupply-client\\node_modules\\apollo-server-core\\src\\requestPipeline.ts:246:30)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (C:\\github\\openmsupply-client\\node_modules\\apollo-server-core\\src\\runHttpQuery.ts:331:24)"]}}}]}
```

**Comment by mark-prins** [comment]
the first issue is already fixed by Josh; the second just needed the api restarted on the demo server, with the typescript compilation the hot reload no longer works; the final issue was a limited number of items showing - and that is due to the reduced limit of items (10-20) combined with the introduction of `isVisible` which will cut that number in half.

Have increased the number of items locally, will pop that in to another fix later.
